Change protostream-core to default scope
The `provided` scope results in the protostream jar not being included
in the shaded build-finder jar and a `NoClassDefFoundError`

```
Error: Unable to initialize main class org.jboss.pnc.build.finder.cli.Main
Caused by: java.lang.NoClassDefFoundError: org/infinispan/protostream/SerializationContextInitializer
```